// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: pb/heartbeat.proto

package heartbeat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeartbeatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request uint32 `protobuf:"varint,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *HeartbeatMessage) Reset() {
	*x = HeartbeatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_heartbeat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatMessage) ProtoMessage() {}

func (x *HeartbeatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_heartbeat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatMessage.ProtoReflect.Descriptor instead.
func (*HeartbeatMessage) Descriptor() ([]byte, []int) {
	return file_pb_heartbeat_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatMessage) GetRequest() uint32 {
	if x != nil {
		return x.Request
	}
	return 0
}

type HeartbeatReplyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State uint32 `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *HeartbeatReplyMessage) Reset() {
	*x = HeartbeatReplyMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_heartbeat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatReplyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReplyMessage) ProtoMessage() {}

func (x *HeartbeatReplyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_heartbeat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReplyMessage.ProtoReflect.Descriptor instead.
func (*HeartbeatReplyMessage) Descriptor() ([]byte, []int) {
	return file_pb_heartbeat_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatReplyMessage) GetState() uint32 {
	if x != nil {
		return x.State
	}
	return 0
}

var File_pb_heartbeat_proto protoreflect.FileDescriptor

var file_pb_heartbeat_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x62, 0x2f, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2c, 0x0a, 0x10, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x2d, 0x0a, 0x15, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x70, 0x62, 0x2f, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61,
	0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_heartbeat_proto_rawDescOnce sync.Once
	file_pb_heartbeat_proto_rawDescData = file_pb_heartbeat_proto_rawDesc
)

func file_pb_heartbeat_proto_rawDescGZIP() []byte {
	file_pb_heartbeat_proto_rawDescOnce.Do(func() {
		file_pb_heartbeat_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_heartbeat_proto_rawDescData)
	})
	return file_pb_heartbeat_proto_rawDescData
}

var file_pb_heartbeat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_heartbeat_proto_goTypes = []interface{}{
	(*HeartbeatMessage)(nil),      // 0: HeartbeatMessage
	(*HeartbeatReplyMessage)(nil), // 1: HeartbeatReplyMessage
}
var file_pb_heartbeat_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_heartbeat_proto_init() }
func file_pb_heartbeat_proto_init() {
	if File_pb_heartbeat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_heartbeat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_heartbeat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatReplyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_heartbeat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_heartbeat_proto_goTypes,
		DependencyIndexes: file_pb_heartbeat_proto_depIdxs,
		MessageInfos:      file_pb_heartbeat_proto_msgTypes,
	}.Build()
	File_pb_heartbeat_proto = out.File
	file_pb_heartbeat_proto_rawDesc = nil
	file_pb_heartbeat_proto_goTypes = nil
	file_pb_heartbeat_proto_depIdxs = nil
}
